# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'MovieBookingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieBookingApp
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 3.5'

end
